version: '3'
services:
  # cnode:
  #   # build:
  #   #   context: .
  #   #   dockerfile: Dockerfile
  #   #   args:
  #   #     - env=value
  #   image: node:12-alpine
  #   command: sh -c "npm run dev"
  #   environment:
  #     - EGG_REDIS_DB=0
  #     - EGG_REDIS_HOST=redis
  #     - EGG_REDIS_PORT=6379
  #     - EGG_REDIS_PASSWORD=egg_cnode
  #     - EGG_MONGODB_URL=mongodb://egg_cnode:egg_cnode@mongodb:27017/egg_cnode
  #     - EGG_PASSPORT_GITHUB_CLIENT_ID=your_github_client_id
  #     - EGG_PASSPORT_GITHUB_CLIENT_SECRET=your_github_client_secret
  #     # - EGG_SITE_STATIC_HOST=${EGG_SITE_STATIC_HOST}

  #   depends_on:
  #     - redis
  #     - mongodb
  #   working_dir: /app
  #   volumes:
  #     - ./:/app
  #   networks:
  #     - docker_cnode
  #   ports:
  #     - 7001:7001

  redis:
    image: redis:3.2-alpine
    command: redis-server --appendonly yes --requirepass egg_cnode
    volumes:
      - egg-redis:/data
    networks:
      - docker_cnode
    ports:
      - 6379:6379

  mysql:
    image: mysql:8.0.28
    volumes:
      - egg-mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: secret
    networks:
      - docker_cnode
    ports:
      - 3306:3306

volumes:
  egg-mysql:
  egg-redis:


networks:
  docker_cnode:
    driver: bridge
